apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml -f ./docker-compose.dev.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: blog
  name: blog
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: blog
