apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker-compose.yml -f ./docker-compose.dev.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: blog
  name: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blog
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker-compose.yml -f ./docker-compose.dev.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: blog
    spec:
      containers:
        - image: blog
          name: blog
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
