
services:
  blog:
    build: 
      context: .
      target: development #use development from Dockerfile
    ports:
      - "3000:3000"
    networks:
      - test-network
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: "blog-database"
    ports:
      - "5432:5432"
    networks:
      - test-network
    volumes:
    - test-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=AdminPassword
    - POSTGRES_USER=Admin
networks:
  test-network:
    driver: bridge
volumes:
  test-data:
    driver: local 


  