# for volume

apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-storage
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

# for database
apiVersion: v1
kind: Deployment
metadata:
  name: database-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-postgres
  template:
    metadata:
        labels:
        app: database-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - port: 5432 # service listen at this port
              targetPort: 5432 # and reference this port of container
          env:
            - name: POSTGRES_PASSWORD
              value: "AdminPassword"
            - name: POSTGRES_USER
              value: "Admin"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-volume-storage
---

### network
apiVersion: v1
kind: Service
metadata:
  name: network
spec:
  type: ClusterIP
  selector:
    matchLabels:
      app: database-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP


### blog-app
---
apiVersion: v1
kind: Deployment
metadata:
  name: blog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      name: blog-service
    spec:
      containers:
        - name: blog-service-container
          image:


---
# ------------------ Service for Blog App ------------------
apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  type: NodePort
  selector:
    matchLabels:
      app: blog
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080